name: celltraj_env
channels:
  - conda-forge
  - defaults
dependencies:
 - python>=3.11
 - numpy
 - h5py
 - matplotlib
 - scipy
 - pip
 - scikit-image
 - scikit-learn
 - scipy
 - pytorch
 - pandas
 - dask
 - pot

